### ISSUE TITLE
Add license??

### ISSUE THREAD

**Issue by bernhardreiter** [fschulze/mr.hermes#2]
Hi Florian,
thanks for publishing code. I guess it is for others to use,
if so you probably should add a license to it.
When in doubt, use an Apache 2.0 license. https://en.wikipedia.org/wiki/Apache_License

I've just considered using mr.hermes and found not license, so it is out of the question for me right now.
(I also want to save emails to maildir.)

Best Regards,
Bernhard

**Comment by fschulze** [comment]
Done.

**Comment by bernhardreiter** [comment]
Cool, thanks!
